Add readme
boltlabs-inc/tss-ecdsa pull request #1
Opened 2022-10-03 18:12 UTC by tyurek

2022-10-11 18:27 UTC, indomitableSwan requested changes
Some minor nits, but otherwise this looks good.

2022-10-11 18:27 UTC, indomitableSwan commented on README.md
> +This repo is a work-in-progress implementation of the UC-Secure threshold ECDSA signing protocol described in https://eprint.iacr.org/2021/060.pdf
Please include the full paper citation as well as the link.

2022-10-11 18:27 UTC, indomitableSwan commented on README.md
> +Currently, the KeyGen protocol (Figure 5), Auxinfo (Figure 6, minus the key refreshing), and 3 round Presign (Figure 7) are implemented, along with the requisite zero-knowledge proofs. These protocol
Specify that you are referencing figures from the paper.

2022-10-11 18:27 UTC, indomitableSwan commented on README.md
> +Currently, the KeyGen protocol (Figure 5), Auxinfo (Figure 6, minus the key refreshing), and 3 round Presign (Figure 7) are implemented, along with the requisite zero-knowledge proofs. These protocol
Add a bit of context for what each of these protocols do. "Auxinfo" is particularly confusing naming.

This section would be better if you rephrase to focus on the implemented functionalities, i.e., if you reference the paper only for additional clarity and as a pointer for readers who would like further detail.

2022-10-11 18:27 UTC, indomitableSwan commented on README.md
> +Currently, the KeyGen protocol (Figure 5), Auxinfo (Figure 6, minus the key refreshing), and 3 round Presign (Figure 7) are implemented, along with the requisite zero-knowledge proofs. These protocol
Also missing period at the end of L9.

2022-10-11 18:27 UTC, indomitableSwan commented on README.md
> +This repo is a work-in-progress implementation of the UC-Secure threshold ECDSA signing protocol described in https://eprint.iacr.org/2021/060.pdf
Missing period at the end of L2.

2022-10-17 13:40 UTC, indomitableSwan requested changes
Thanks for updating. Still a few minor comments left to be resolved, and a question.

2022-10-17 13:40 UTC, indomitableSwan commented on README.md
> +This repo is a work-in-progress implementation of the ECDSA signing protocol described in "UC Non-Interactive, Proactive, Threshold ECDSA with Identifiable Aborts" [CGGMP] which can be found at https
I really mean the full citation. Including author names, venue published, etc.

2022-10-17 13:40 UTC, indomitableSwan commented on README.md
> +Auxinfo generates the auxilary information (such as Paillier keys) needed in order to compute presignatures. In CGGMP, this is done in parallel with key refreshing, however this codebase currently on
Please be more specific as to what the Auxinfo contains.

2022-10-17 13:40 UTC, indomitableSwan commented on README.md
> +This repo is a work-in-progress implementation of the ECDSA signing protocol described in "UC Non-Interactive, Proactive, Threshold ECDSA with Identifiable Aborts" [CGGMP] which can be found at https
Include the year published in the shorthand reference name.

2022-10-17 13:40 UTC, indomitableSwan commented on README.md
> +Auxinfo generates the auxilary information (such as Paillier keys) needed in order to compute presignatures. In CGGMP, this is done in parallel with key refreshing, however this codebase currently on
Question: Is key refreshing implemented in this codebase?

2022-10-17 13:40 UTC, indomitableSwan commented on README.md
> +KeyGen, Auxinfo, and Presign are the three protocols needed in order to do threshold signing. All of the zero-knowledge proofs that underpin these protocols have been implemented, as has a echo-broad
typo: "a echo-" --> "an echo-"

2022-10-17 13:42 UTC, indomitableSwan commented
Also -- can you fix so that the CI checks pass?

2022-10-17 19:25 UTC, tyurek commented on README.md
> +Auxinfo generates the auxilary information (such as Paillier keys) needed in order to compute presignatures. In CGGMP, this is done in parallel with key refreshing, however this codebase currently on
It is not

2022-10-19 15:01 UTC, indomitableSwan requested changes
Thanks for the changes; this is much improved. Almost there.

2022-10-19 15:01 UTC, indomitableSwan commented on README.md
> +Auxinfo generates the auxilary information (Paillier keys and ring-Pedersen parameters) needed in order to compute presignatures. In CGGMP, this is done in parallel with key refreshing, however this
CGGMP20

2022-10-20 16:24 UTC, tyurek commented on README.md
> +This repo is a work-in-progress implementation of the ECDSA signing protocol described in "UC Non-Interactive, Proactive, Threshold ECDSA with Identifiable Aborts" [CGGMP20] which can be found at htt
Can you give an example of what this would look like?

2022-10-21 19:53 UTC, indomitableSwan commented on README.md
> +This repo is a work-in-progress implementation of the ECDSA signing protocol described in "UC Non-Interactive, Proactive, Threshold ECDSA with Identifiable Aborts" [CGGMP20] which can be found at htt
quickest, maybe non-awkward fix:

This repo is a work-in-progress implementation of Canetti et al.'s threshold ECDSA protocol described in

[CGGMP20] R. Canetti, R. Gennaro, S. Goldfeder, N. Makriyannis, and U. Peled. UC non-interactive, proactive,  threshold ECDSA with identifiable aborts. In  ACM CCS 2020, pp. 1769–1787. ACM Press, 2020.

For details, see the [paper](https://eprint.iacr.org/2021/060.pdf).

2022-10-21 19:53 UTC, indomitableSwan commented on README.md
> +This repo is a work-in-progress implementation of the ECDSA signing protocol described in "UC Non-Interactive, Proactive, Threshold ECDSA with Identifiable Aborts" [CGGMP20] which can be found at htt
i.e. and just delete the reference section, if we're not going to have any other references.

2022-10-24 15:10 UTC, indomitableSwan approved these changes
LGTM. Thanks for updating.

2022-10-24 17:52 UTC, merged