Update readme
boltlabs-inc/tss-ecdsa pull request #270
Opened 2023-04-11 18:36 UTC by hridambasu

Updated readme file by adding instructions on how to build and run. Also added pointers for benchmarks and examples.

2023-04-11 22:55 UTC, amaloz reviewed
Some minor comments / suggestions.

2023-04-11 22:55 UTC, amaloz commented on README.md
> +The preferred Rust version is cargo 1.68.2.
If we have a preferred rust version, should we instead pin it using the `rust-toolchain` file?

2023-04-11 22:55 UTC, amaloz commented on README.md
> +###  What's Implemented
I think this has one extra heading level, should be ## instead?

2023-04-11 22:55 UTC, amaloz commented on README.md
> +Auxinfo generates the auxilary information (Paillier keys and ring-Pedersen parameters) needed in order to compute presignatures. In CGGMP20, this is done in parallel with key refreshing, however thi
I think the correct spelling is "auxiliary" :-)

2023-04-12 14:05 UTC, marsella requested changes
Thanks for this PR! These are super useful additions. Most of my comments are sharing context that you didn't have, with some recommendations on making phrasing more specific.

2023-04-12 14:05 UTC, marsella commented on README.md
> +`rustup update`
nit: The first command here does what you said (switch to stable); the second updates the version. I think it's still useful to have both, but consider updating the text above to be clear about that, e.g.
> The library requires a recent, stable version of Rust. You can switch to stable releases and update to the latest version using the following:

2023-04-13 15:34 UTC, marsella commented on README.md
> +
@hridambasu Did you figure anything out about this?

2023-04-13 17:51 UTC, hridambasu commented on README.md
> +
I also think the latter that gmp does not auto install via the gmp-mpfr-sys crate. So shall I include this link for installation - https://formulae.brew.sh/formula/gmp?

2023-04-13 18:19 UTC, marsella commented on README.md
> +
Brew is only for OSX, so we need more than just that link. Unfortunately the gmp docs only have [instructions for downloading from source](https://gmplib.org/manual/Installing-GMP). [This site](http://www.mathemagix.org/www/mmdoc/doc/html/external/gmp.en.html) has some other Ubuntu commands for downloading the package and a separate option for OSX. Maybe the best approach is a little paragraph that's like, you can build from source \<link to GMP docs\> or using a package manager on linux \<link to mathemagix\> or OSX \<link to brew\>. The GMP website has [additional notes for other systems](https://gmplib.org/manual/Notes-for-Particular-Systems).

2023-04-13 19:55 UTC, merged