Threaded Example: Refactors code and adds support for multiple concurrent subprotocols.
boltlabs-inc/tss-ecdsa pull request #343
Opened 2023-05-04 18:16 UTC by gatoWololo

Makes work toward #319 

Refactors code and adds support for multiple concurrent subprotocols and multiple storage.

2023-05-04 18:29 UTC, gatoWololo commented
@tposavec check out the newest version of our threaded example here to get a sense of all that has to happen to drive this library and the protocol!

2023-05-09 13:39 UTC, marsella reviewed
This looks pretty good to me but to be honest it's a lot of code and I'm not super confident in my review. It would help if we could have a quick call to talk through how the concurrency support works. 

Could you please check off the boxes that this completes in #319?

2023-05-10 18:49 UTC, marsella requested changes
Thanks for walking me through this today. I have a few comments that we discussed.

2023-05-10 18:49 UTC, marsella commented on examples/threaded_example/threaded.rs
> +struct KeyId(Identifier);
We discussed this and I recommend using the [uuid crate](https://docs.rs/uuid/latest/uuid/) instead of `Identifier`.

2023-05-10 18:49 UTC, marsella commented on examples/threaded_example/threaded.rs
> +        let mut sub_protocol_ended = 0;
todo: We discussed on a call that this singular output counter means that the coordinator itself doesn't support concurrent protocol executions, even though the workers do. Please make a new issue about adding coordinator support for concurrency.

2023-05-10 18:49 UTC, marsella commented on examples/threaded_example/threaded.rs
> +    /// thread via our `self.send_to_workers` map.
suggestion: You might add a bit of documentation here to mention that this does not do any authentication of messages (to ensure that the sender is who they say they are).

2023-05-10 18:49 UTC, marsella commented on examples/threaded_example/threaded.rs
> +//! amongst threads.
todo: Add documentation up here about the trust model of this example. Specifically, this example does not implement sender authentication, which is required for a secure deployment. This means that
1. The coordinator is trusted to route messages correctly.
2. The workers are trusted to not forge messages from other participants.

2023-05-22 13:20 UTC, marsella approved these changes
Looks good to me!

2023-05-22 17:39 UTC, merged