PiLog Tests
boltlabs-inc/tss-ecdsa pull request #386
Opened 2023-05-23 20:41 UTC by hridambasu

Closes #110

2023-05-24 17:25 UTC, marsella requested changes
Thank you, this is a good start! These tests can be quite fiddly so many of my comments are naming / documentation tweaks. I also think we're missing a couple of tests:
- the negative side of the range proof
- the bad-rho half of the "you need to know the secret input" test
- the whole common-input-must-match test.

2023-05-24 17:25 UTC, marsella commented on src/zkp/pilog.rs
> +        // Swap mask_commit with a random [`Commitment`]
nit: fix comment.

2023-05-24 17:25 UTC, marsella commented on src/zkp/pilog.rs
> +    fn negative_test_swap_proof_elements() -> Result<()> {
This test looks great!

2023-05-24 17:25 UTC, marsella commented on src/zkp/pilog.rs
> +        assert!(bad_proof.verify(&input, &(), &mut transcript).is_err());*/
Oops, never mind, I started reviewing too soon.

2023-05-25 15:41 UTC, marsella requested changes
Thanks, this looks better! I have a few more refactoring / renaming kinds of comments.

2023-05-30 19:23 UTC, marsella requested changes
Thanks, this is looking much better. Only one small comment on your work but I realized two things:
1. Transcripts are not being initialized correctly throughout -- we should use a better paradigm to make sure each prove/verify call gets a fresh transcript (see comment inline)
2. We had different ideas about what the setup parameters test should be testing. Would like your thoughts on what the meaningful failure conditions of the proofs are (and how that informs which tests we should write).

2023-05-31 07:33 UTC, hridambasu commented
> 2. We had different ideas about what the setup parameters test should be testing. Would like your thoughts on what the meaningful failure conditions of the proofs are (and how that informs which tests we should write).

I can add another test to mimic the exact sequence of events in the different setup parameters test by creating a valid proof first and then asserting that the proof fails to verify if one of the input fields are modified. But honestly after the test that I added, it seems a bit redundant. But I can also add that test in addition to my test or modify my test with the one you suggested.

2023-05-31 14:07 UTC, marsella approved these changes
We talked about the common-input test offline -- the tests would test separate things: this one checks that you can't create a proof that passes if your input is wrong, and the one I suggested checks that you can't verify a valid proof if you have the wrong input. We decided that the latter is not a high priority test for this setting because of how it could happen (either something gets messed up in transit, or a malicious prover lies to the verifier and causes their own proof to fail, or a malicious verifier takes an extremely roundabout way to just abort), so we'll skip it.

Otherwise this looks good!

2023-05-31 14:07 UTC, marsella commented on src/zkp/pilog.rs
> +    //use k256::elliptic_curve::bigint::Random;
todo: remove commented-out code.

2023-05-31 15:07 UTC, merged