Clean up documentation for example code.
boltlabs-inc/tss-ecdsa pull request #392
Opened 2023-05-24 23:58 UTC by gatoWololo

Closes #380

2023-05-25 16:04 UTC, marsella requested changes
This is a great improvement! The updated type names throughout are much better and make the whole example easier to understand, in my opinion.

2023-05-25 16:04 UTC, marsella commented on examples/threaded_example/threaded.rs
issue: I think the top-level documentation's Trust Model section (or maybe documentation on the `Coordinator`? whichever you think is more likely to be read by someone looking at the example) should note that a coordinator is not _necessary_ to run the library. Something like,

> A trusted `Coordinator` is not required to run threshold ECDSA protocol. Networking models with less trust include authenticated point-to-point channels between the workers or an untrusted relay node that routes authenticated messages between the workers.

2023-05-25 19:37 UTC, gatoWololo commented on examples/threaded_example/threaded.rs
> +/// Coordinator responsible for running sub-protocols.
That totally makes sense!

2023-05-26 13:47 UTC, marsella approved these changes
Looks good, thanks for addressing!

2023-05-26 20:35 UTC, merged