Switch over pilog to use better proof trait: `Proof2`
boltlabs-inc/tss-ecdsa pull request #404
Opened 2023-06-02 23:51 UTC by gatoWololo

Closes #397

2023-06-05 19:20 UTC, marsella requested changes
Thanks! A couple notes here, the only blocking change is making sure the docs on `ProverSecret` are up to date.

2023-06-05 19:20 UTC, marsella commented on src/zkp/pilog.rs
> +        let proof =
suggestion: use the `transcript()` method here.

2023-06-05 19:20 UTC, marsella commented on src/presign/participant.rs
> +        public.clone().verify(
note: This seemed weird to me and I think we should change this API at some point, but for now I [made a comment](https://github.com/boltlabs-inc/tss-ecdsa/issues/352#issuecomment-1577346861) on the most relevant issue.

2023-06-06 18:52 UTC, gatoWololo commented on src/zkp/pilog.rs
> +pub(crate) struct ProverSecret<'a> {
Whoops. You are right, no need to do it if it's not needed!

2023-06-06 18:57 UTC, gatoWololo commented on src/zkp/pilog.rs
> +    pub(crate) fn new(plaintext: &'a BigNumber, nonce: &'a Nonce) -> ProverSecret<'a> {
Oh interesting, I'm actually not super familiar with the exact way lifetimes are needed in this case. I originally wrote it like `Self<'a>` but the compiler complained:
```rust
error[E0109]: lifetime arguments are not allowed on self type
   --> src/zkp/pilog.rs:132:75
    |
132 |     pub(crate) fn new(plaintext: &'a BigNumber, nonce: &'a Nonce) -> Self<'a> {
    |                                                                      ---- ^^ lifetime argument not allowed
    |                                                                      |
    |                                                                      not allowed on self type
    |
note: `Self` is of type `zkp::pilog::ProverSecret<'a>`
   --> src/zkp/pilog.rs:114:19
    |
114 | pub(crate) struct ProverSecret<'a> {
    |                   ^^^^^^^^^^^^ `Self` corresponds to this type
...
130 | impl<'a> ProverSecret<'a> {
    | ------------------------- `Self` is on type `ProverSecret` in this `impl`
help: the `Self` type doesn't accept type parameters, use the concrete type's name `ProverSecret` instead if you want to specify its type parameters
    |
132 |     pub(crate) fn new(plaintext: &'a BigNumber, nonce: &'a Nonce) -> ProverSecret<'a> {
    |                                                                      ~~~~~~~~~~~~
```
So I changed it to `ProverSecret<'a>` but you are right that it works with just `Self`. So the lifetime is inferred? :mask:

2023-06-06 18:57 UTC, gatoWololo commented on src/zkp/pilog.rs
> +    pub(crate) fn new(plaintext: &'a BigNumber, nonce: &'a Nonce) -> ProverSecret<'a> {
Anyways... I changed it!

2023-06-06 21:21 UTC, marsella commented on src/zkp/pilog.rs
> +pub(crate) struct ProverSecret<'a> {
Thank you for your commitment to documentation anyway :pray:

2023-06-06 21:22 UTC, marsella approved these changes
Thanks, looks good!

2023-06-06 23:08 UTC, merged