288-remove
boltlabs-inc/tss-ecdsa pull request #409
Opened 2023-06-07 06:21 UTC by tyurek

Adds a new `remove()` function to the Storage API, which removes an item from storage and returns it to the call. Replaces a few end-of-protocol calls to `retrieve` with `remove`, but only where there is no chance that the item will be needed again. Replacing other instances of `retrieve` with `remove` will require more care, especially when considering the possibility of `ProtocolError`s

2023-06-07 15:20 UTC, marsella approved these changes
Looks good to me! One small note for your consideration.

2023-06-07 15:20 UTC, marsella commented on src/local_storage.rs
> +    /// if it existed and should be used instead of retrieve if the value is
suggestion: link to retrieve here ```[`retrieve()`](LocalStorage::retrieve())```

2023-06-07 15:21 UTC, marsella requested changes
Oh sorry, one more thing:

I think you can also remove the `r3_private` and `r3_pubs` in `do_presign_finish`. Is there a reason you skipped those?

2023-06-08 15:35 UTC, tyurek commented
After r3_pubs and r3_private are retrieved, there are still checks that need to be done which can fail with ProtocolError. I didn't remove these values, so to avoid figuring out what to do with them in this case

2023-06-08 15:50 UTC, marsella approved these changes
Thanks, I misread the code and thought you could still remove the `private`, but now I see that's not the case.

2023-06-12 13:35 UTC, merged