generalize-curve: move CurvePoint behind a trait
boltlabs-inc/tss-ecdsa pull request #557
Opened 2024-12-29 17:12 UTC by naure

- Introduce a trait (temp. name `CT`).
- Add the generic type (`<C>`) everywhere.
- Extract curve operations into the trait. This is not a full curve trait, rather it represents exactly the needs of the library.

2025-01-30 22:17 UTC, gatoWololo requested changes
Hello,

I left some minor feedback. Overall this looks good to me. This change is very impressive. It adds quite a bit of complexity specially with the Generics + associated types and lifetimes. But it all seems to work. And IDK how we would do this any simpler.

My only real thought. I notice we have a pattern of `C: CurveTrait + 'static` throughout. I wonder if it would be possible to fold in the `'static` lifetime as part of the definition on trait `CurveTrait`. This way we wouldn't need to list it in so many places (IDK this may not work). The observation is that we don't have a use case for our `C: CurveTrait` to ever have a non-static lifetime, i.e some reference.

2025-01-30 22:17 UTC, gatoWololo commented on src/protocol.rs
> +        // TODO: try_from_bytes only works for K256, we need to make it work for P256
Left over TODO

2025-02-03 10:47 UTC, emmorais commented on src/presign/record.rs
> +                    .expect("Failed to parse scalar from bytes"),
done

2025-02-03 10:47 UTC, emmorais commented on src/presign/round_three.rs
> +    //#[serde(bound(deserialize = "C: CT"))]
removed

2025-02-03 10:56 UTC, emmorais commented on src/auxinfo/proof.rs
> +    #[serde(bound(deserialize = "C: CurveTrait"))]
Yes, this was a hurdle during refactoring, because the wrapped component has a different implementation for deserialize, which is less efficient than the one we chose to use. This line allows to choose which one will be used. Otherwise the code would not compile, and fixing it would be more complicated.

2025-02-03 10:57 UTC, emmorais commented on src/auxinfo/proof.rs
> +pub(crate) struct CommonInput<'a, C: CurveTrait + 'a + 'static> {
Nice catch! It was only temporarily necessary while the generalization wasn't fully propagated. Thanks!

2025-02-03 10:58 UTC, emmorais commented on src/sign/interactive_sign/participant.rs
> +    where
Nice catch again! It was removed.

2025-02-03 10:58 UTC, emmorais commented on src/auxinfo/proof.rs
> +pub(crate) struct CommonInput<'a, C: CurveTrait + 'a + 'static> {
This lifetime bound was removed.

2025-02-03 11:02 UTC, emmorais commented on src/slip0010/ckd.rs
> +    // assert the public key (TODO: it only works for K256)
The test vector was commented out because it is known it would not work for P256. Now this indeed only runs for K256, and the TODO was only for stop running it for P256. Since this problem was solved before, the TODO was old. Therefore I removed it.

2025-02-03 11:02 UTC, emmorais commented on src/slip0010/ckd.rs
> +    // assert the chain code (TODO: it only works for K256)
removed

2025-02-03 11:02 UTC, emmorais commented on src/slip0010/ckd.rs
> +    // assert the private key (TODO: it only works for K256)
removed

2025-02-03 11:30 UTC, emmorais commented on src/protocol.rs
> +        // TODO: try_from_bytes only works for K256, we need to make it work for P256
removed

2025-02-03 12:48 UTC, emmorais commented
> Hello,
> 
> I left some minor feedback. Overall this looks good to me. This change is very impressive. It adds quite a bit of complexity specially with the Generics + associated types and lifetimes. But it all seems to work. And IDK how we would do this any simpler.
> 
> My only real thought. I notice we have a pattern of `C: CurveTrait + 'static` throughout. I wonder if it would be possible to fold in the `'static` lifetime as part of the definition on trait `CurveTrait`. This way we wouldn't need to list it in so many places (IDK this may not work). The observation is that we don't have a use case for our `C: CurveTrait` to ever have a non-static lifetime, i.e some reference.

Indeed moving static to CurveTrait allowed to remove a lot of repeated code. Thank you.

2025-02-10 23:30 UTC, jakinyele approved these changes
LGTM!

2025-02-11 16:33 UTC, gatoWololo approved these changes

2025-02-11 16:34 UTC, merged